### PR TITLE
Fix public authorization header

### PR DESCRIPTION
**Pull request by vasconita**
https://github.com/unsplash/unsplash-js/issues/62

### CODE REVIEW

**Comment by Ding-Fan** [comment]
What's the situation here? Is there something wrong with @vasconita 's commit? Issue #62 still exist 🤔

**Comment by lukechesser** [comment]
Thanks for PR-ing this @vasconita.

The thing we're internally debating is how to best fix this, given that users who have previously used the `applicationId` will likely not change it, leading them to making unauthorized requests or at the very least causing a lot of confusion. There's a few ideas we have for it, but just to give you an update, that's what we're debating internally.

cc @Ding-Fan

**Comment by louim** [comment]
@lukechesser any progress on this? We encountered this error today when trying to setup Unsplash-js.

**Comment by lukechesser** [comment]
@louim yeah so we've briefly updated the documentation, but it's still not a good enough fix for long term.

Our thinking is to create a `2.0` of the library that fixes a few other issues, including this one, since it would be a breaking change.

Unfortunately, not sure on the ETA of it

**Pull request closed without merging**
