### PR TITLE
add collections and orientation params to unsplash.search.photos

### PR DESCRIPTION
**Pull request by chrisyer**
#### Overview

add orientation and collections as a parameter to the `unsplash.search.photos` query, based on [Unsplash Developer Document](https://unsplash.com/documentation#search-photos)

Releated issue #55

### CODE REVIEW

**Comment by Haitaar** [comment]
Hi there! Any update on this?

**Comment by chrisyer** [comment]
I split `searcher` to `universalSearcher` and `photosSearcher`
https://github.com/unsplash/unsplash-js/blob/master/src/methods/search.js
@Haitaar

**Comment by vincentdesmares** [comment]
It looks like the CI failed for reasons unrelated to the code

```Couldn't find the binary node ./npm-scripts/postinstall.js```

Anyway, @chrisyer, the yarn.lock should not be modified with the Chinese npm repository:

```registry.npm.taobao.org```

**Comment by lukechesser** [comment]
@chrisyer @Haitaar sorry about this, I somehow didn't see the multiple updates on this. Really sorry.

@vincentdesmares yes for sure. There's a few small things I would clean up, but I can add those in a next PR if that makes sense.

Fwiw, we are maintaining this repository, but we have plans to replace it with a rewrite that has some breaking changes. The majority of the features aren't being used, so we could definitely simplify it.

**Comment by lukechesser** [comment]
Thanks for PR-ing this. It finally made it's way into a major update for #112

**Pull request closed without merging**
