### PR TITLE
Adding topics to getRandom

### PR DESCRIPTION
**Pull request by moonrise-tk**
#### Overview

Yo. I'm trying to add topicIds support to the `getRandom` endpoint. No idea if I'm going about it right. I also keep running into this error (unrelated to the code I wrote) while building:
```
/src/helpers/errors.ts(24,5): semantic error TS2322:
Type 'NonEmptyArray<AnyJson> | null' is not assignable to type 'Nullable<NonEmptyArray<string>>'.
  Type 'NonEmptyArray<AnyJson>' is not assignable to type 'Nullable<NonEmptyArray<string>>'.
   Type 'AnyJson' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.
```
I'm not sure what the issue is after looking at the file referenced.

#### Todo

Add docs and tests.

If someone can verify I'm doing this the right way, I can add docs and tests and finish up the PR.

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Thanks, this looks good to me!

> I also keep running into this error (unrelated to the code I wrote) while building:

I'm not sure what's going on there. Are you using the TS version bundled in `node_modules`?

**Comment by moonrise-tk** [comment]
I think I am, but the typescript version bundled in node_modules is 3.9, not 4.2 like in your screenshot:

Screen Shot 2021-07-14 at 6 51 57 PM

**Comment by Magellol** [comment]
@moonrise-tk Have you run yarn to update any dependencies? That might solve that issue.

**Comment by moonrise-tk** [comment]
Ah shoot yall are using yarn, not npm. Works now :). I'll finish up the PR.

**Comment by moonrise-tk** [comment]
Done! I didn't add tests because I guess you can't do without the API key, but I tried it, and it seems to be working. Let me know if it looks okay! Also I updated the types for `collectionIds` and `topicIds` to be `Array<string>` in the README. I think they are strings: https://unsplash.com/documentation#get-a-topic.

**Review by OliverJAsh — APPROVED** [review]
Thanks again!

**Comment by OliverJAsh** [comment]
https://github.com/unsplash/unsplash-js/releases/tag/v7.0.14

**Comment by moonrise-tk** [comment]
I'm really confused: when I use the newest release of unsplash-js in my project, the distribution does not include the new topic ids param. When I `yarn run build` my fork, the `dist` folder does update. When I check in the `src` folder in the node_modules of my project, the new topicIds code shows up. 

Screen Shot 2021-07-15 at 5 31 47 PM
The typing in node_modules/unsplash-js/dist/index.d.ts in my project. It does not use the new topicIds param. Incorrectly typed.

Screen Shot 2021-07-15 at 5 33 59 PM
The typing in node_modules/unsplash-js/dist/methods/photos/index.d.ts. The distributed code exports the new param. Correctly typed.

Screen Shot 2021-07-15 at 5 35 02 PM
The typing of `getRandom` in dist/index.d.ts when I run `yarn run build` on my fork. Correctly typed.

What's going on? Is there somewhere else I need to update types?

**Comment by moonrise-tk** [comment]
(Also i've tried cleaning my npm cache, uninstalling, reinstalling, everything)

**Comment by OliverJAsh** [comment]
@moonrise-tk I'm sorry, we have a problem with our build tool: https://github.com/unsplash/unsplash-js/issues/167

I've just published a new version, this should work!

https://github.com/unsplash/unsplash-js/releases/tag/v7.0.15

To verify: https://unpkg.com/unsplash-js@7.0.15/dist/index.d.ts

**Pull request merged**
