### PR TITLE
Photo random orientation parameter

### PR DESCRIPTION
**Pull request by dechuck**
- Add orientation parameter in random photos
- replica of #27

### CODE REVIEW

**Comment by dechuck** [comment]
@lukechesser Could you merge and push it to NPM?

**Comment by lukechesser** [comment]
@dechuck shared creds are in meldium!

**Comment by joshwcomeau** [comment]
Soooo... what's the deal with this guy? Haha. I don't know the background story, but it sounds like it's good to merge/deploy?

I can see the appeal of supporting landscape/portrait in the random photo endpoint.

**Comment by lukechesser** [comment]
Yup I think it's good to go. I think we just never merged and published to npm.

**Pull request merged**
